modify indentation

diff --git a/goruc b/goruc
--- a/goruc
+++ b/goruc
@@ -1,95 +1,84 @@
 #!/bin/bash
 
+
 oneline_usage="$0 [options]"
 login_addr="http://10.12.16.122"
 jump_addr="http://10.12.16.126:801"
 
-usage()
-{
-	cat	<<-USAGEEOF
-			Usage: $oneline_usage
-			Try "$0 -h" for more information.
-		USAGEEOF
-	exit 2
+usage() {
+  cat  <<-USAGEEOF
+	Usage: $oneline_usage
+	Try "$0 -h" for more information.
+	USAGEEOF
+  exit 2
 }
 
-help()
-{
-	cat <<-HELPEOF
-			Usage: $oneline_usage
-			
-			options:
-			-i    login
-			-o    logout
-			-h    help
-		HELPEOF
-	exit 0
+help() {
+  cat  <<-HELPEOF
+	Usage: $oneline_usage
+
+	options:
+	-i    login
+	-o    logout
+	-h    help
+	HELPEOF
+  exit 0
 }
 
-err()
-{
-	echo $@
-	exit 1
+err() {
+  echo $@
+  exit 1
 }
 
-if [ $# -eq 0 ]
-then
-	usage
+if [ $# -eq 0 ]; then
+  usage
 fi
 
-while getopts "ioh" opt
-do
-	case $opt in
-	i)
-		if [ ! -f COOKIE ]
-		then
-			response=$(curl -s -c COOKIE -L $jump_addr/eportal/index.php)
-		fi
-		read -p "Username: " username
-		read -p "Password: " -s password
-		echo
-		response=$(curl -s -b COOKIE -L $login_addr -d "DDDDD=$username&upass=$password&0MKKey=123456&R6=0")
-		if [[ $response =~ "successfully logged into" ]]
-		then
-			echo ">> Succeed!"
-		else
-			err ">> Authentication failed, wrong username or password."
-		fi
-		response=$(curl -s -b COOKIE -L $jump_addr/eportal/ruc/index.php -d "UID=$username&password=&is_lack=0")
-		if [[ $response =~ "php/RucSetting.php" ]]
-		then
-			echo ">> You can connect to internet now :)"
-		else
-			err ">> An error occured :("
-		fi
-		exit 0
-		;;
-	o)
-		if [ ! -f COOKIE ]
-		then
-			err ">> COOKIE missed, please login first."
-		fi
-		response=$(curl -s -b COOKIE -L $jump_addr/eportal/ruc/php/get_user_device.php)
-		if ! [[ $response =~ "\"result\":\"ok\"" ]]
-		then
-			err ">> You're not online or the session expired, please login first."
-		fi
-		sid=$(echo $response | grep -Po '"online_session":.*?[^\\]",' | head -n 1 | grep -o -E '[0-9]+' | head -n 1)
-		echo $sid
-		response=$(curl -s -b COOKIE -L $jump_addr/eportal/ruc/php/offline_device.php -d "is_auto_login=0&device_list=1|$sid")
-		if [[ $response =~ "\"result\":\"ok\"" ]]
-		then
-			echo ">> Logged out successfully."
-		else
-			err ">> Unknown error."
-		fi
-		exit 0
-		;;
-	h)
-		help
-		;;
-	*)
-		usage
-		;;
-	esac
+while getopts "ioh" opt; do
+  case $opt in
+    i)
+      if [ ! -f COOKIE ]; then
+        response=$(curl -s -c COOKIE -L $jump_addr/eportal/index.php)
+      fi
+      read -p "Username: " username
+      read -p "Password: " -s password
+      echo
+      response=$(curl -s -b COOKIE -L $login_addr -d "DDDDD=$username&upass=$password&0MKKey=123456&R6=0")
+      if [[ $response =~ "successfully logged into" ]]; then
+        echo ">> Succeed!"
+      else
+        err ">> Authentication failed, wrong username or password."
+      fi
+      response=$(curl -s -b COOKIE -L $jump_addr/eportal/ruc/index.php -d "UID=$username&password=&is_lack=0")
+      if [[ $response =~ "php/RucSetting.php" ]]; then
+        echo ">> You can connect to internet now :)"
+      else
+        err ">> An error occured :("
+      fi
+      exit 0
+      ;;
+    o)
+      if [ ! -f COOKIE ]; then
+        err ">> COOKIE missed, please login first."
+      fi
+      response=$(curl -s -b COOKIE -L $jump_addr/eportal/ruc/php/get_user_device.php)
+      if ! [[ $response =~ "\"result\":\"ok\"" ]]; then
+        err ">> You're not online or the session expired, please login first."
+      fi
+      sid=$(echo $response | grep -Po '"online_session":.*?[^\\]",' | head -n 1 | grep -o -E '[0-9]+' | head -n 1)
+      response=$(curl -s -b COOKIE -L $jump_addr/eportal/ruc/php/offline_device.php -d "is_auto_login=0&device_list=1|$sid")
+      if [[ $response =~ "\"result\":\"ok\"" ]]; then
+        echo ">> Logged out successfully."
+      else
+        err ">> Unknown error."
+      fi
+      exit 0
+      ;;
+    h)
+      help
+      ;;
+    *)
+      usage
+      ;;
+  esac
 done
